[tasks.build]
clear = true
script = [
"""
#!/usr/bin/env bash
echo "args are $@";
docker run --rm --user "$(id -u)":"$(id -g)" -e CARGO_HOME=/usr/src/myapp/target/.cache -v "$PWD":/usr/src/myapp -w /usr/src/myapp rust-build cargo build $@
"""
]

[tasks.test]
clear = true
script = [
"""
#!/usr/bin/env bash
docker run --rm --user "$(id -u)":"$(id -g)" -e "RUST_BACKTRACE=1" -e CARGO_HOME=/usr/src/myapp/target/.cache -v "$PWD":/usr/src/myapp -w /usr/src/myapp rust-build cargo test -- --nocapture
"""
]
