[tasks.build]
clear = true
script = [
"""
#!/usr/bin/env bash
echo "args are $@";
docker run --rm --user "$(id -u)":"$(id -g)" -e CARGO_HOME=/usr/src/myapp/target/.cache -v "$PWD":/usr/src/myapp -w /usr/src/myapp rust-build cargo build $@
"""
]

[tasks.test]
clear = true
script = [
"""
#!/usr/bin/env bash
docker run --rm --user "$(id -u)":"$(id -g)" -e "RUST_BACKTRACE=1" -e CARGO_HOME=/usr/src/myapp/target/.cache -v "$PWD":/usr/src/myapp -w /usr/src/myapp rust-build cargo test -- --nocapture
"""
]

[tasks.deploy]
dependencies = [
    "build"
]
script = [
"""
#!/usr/bin/env bash
scp -P 2222 target/debug/libnss_iam_user.so l@localhost:~
ssh l@localhost -p2222 sudo bash << 'EOF'
cp libnss_iam_user.so /lib/x86_64-linux-gnu/libnss_iam_user.so.2
ldconfig
id unknown || true
tail -n10 /opt/bar.txt
exit 0
EOF
"""
]
